[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tc_model"
version = "0.1.0"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
test = ["pytest"]
